name = "Blogosphere"
license = "MIT"
licenselink = "https://github.com/mschoenlaub/hugo-theme-blogosphere/blob/master/LICENSE"
description = "A simple, bootstrap 4 based blog theme suitable for multiple authors."
homepage = "https://github.com/mschoenlaub/hugo-theme-blogosphere/"
tags = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light"]
features = ["minimal", "minimalist", "blog", "responsive", "syntax highlighting", "multilingual", "minimalist", "light"]
min_version = "0.41.0"

[author]
  name = "mschoenlaub"
  homepage = "https://schoenlaub.info"